name: mercadopago_sdk
description: MercadoPago Dart SDK
author: Israel Lugo <hostelixisrael@gmail.com>
homepage: https://github.com/bmkeros/mercadopago_sdk_dart
version: 1.0.0

dependencies:
  http: ^0.12.0

environment:
  sdk: ">=2.0.0 <3.0.0"
