name: mercadopago_sdk
description: >-
  Mercadopago SDK module for Payments integration
  for use in applications web, server, flutter
homepage: https://github.com/bmkeros/mercadopago_sdk_dart
version: 1.2.3

dependencies:
  http: ^0.12.0
  test: ^1.5.1+1

environment:
  sdk: ">=2.0.0 <3.0.0"
